### ISSUE TITLE
Running tasktree deleted projects info for all tasks

### ISSUE THREAD

**Issue by maciejmotyka** [maralorn/tasktree#5]
I've installed the `tasktree` according to the instructions, added it to path and added the recommended two lines to `~/.taskrc`. I then run `tasktree` performed few queries and exited.
Immediatelly after this I run `task` and realized that all information about projects is missing. When I use `task info` I see `2020-05-14 15:04:06 Project deleted.`. All my tasks that were a part of any project have this information. Running `task projects` reports `0 projects (51 tasks)`.

Is this intended behavior?

I'm on Ubuntu MATE 20.04

**Comment by maralorn** [comment]
I am very sorry. Yes, that was intended behavior.
I probably need to have a big warning in the README.
I actually didn‘t expect this tool to be used by anyone anymore, I haven‘t used it myself for years.

When you sort the tasks into a tree the projects will be set by the name of the parent tasks. But since at the first time you run tasktree your task list is flat and no task has a parent, this leads to all calculated projects being empty.

**Comment by maciejmotyka** [comment]
No hard feelings, I had only 5 projects, so adding them back was quick.

Anyway, I think adding this warning to README is a great idea.

**Comment by maralorn** [comment]
I added it.
